### ISSUE TITLE
hi TOI

### ISSUE THREAD

**Issue by madymaxion** [dherrendoerfer/TOI_Firmware#1]
I could start the webserver, but as soon as i trigger a GET request, for example setting time.  I get "Timeout" in Debug many times and after that my cactus micro disappears from device list. 

GET /c2ct.html?ch=15&cm=0&cd=6&cb=1000000 HTTP/1.1
...
Accept-Language: en-US,en;q=0.8,de;q=0.6
Timeout
Timeout
Timeout

I have to unplug and plug the cactus to have it up running again. 

Hardware Serial is set, other wise no pin connected. Do i have to Connect any pins if i do not intend to flash the firmware of the esp because it has already the needed firmware on it? 

And which PIN would be the ESP mode select? Could not find any info about it on AB-Wiki. 

Any hint/help would be appreciated. 

Thx
Marc

**Comment by dherrendoerfer** [comment]
Depending on the client you may want to increase the Packet buffer size;

/\* Input Buffer size for the web server */
#define M_BUFFER_SIZE 500

The modifications for using the flasher mode are available
here:
http://blog.aprbrother.com/p/283
The only difference is that you need to connect GPIO0 to PIN15
on the Arduino Board.

Flashing can then be done via:
sudo ./esptool.py -p /dev/ttyACM0 -b 115000 write_flash 0x000000 ./ai-thinker-0.9.5.2-9600.bin
More information is also available on the aprbrother web site.
Dirk

**Comment by madymaxion** [comment]
Tried with:
#define M_BUFFER_SIZE 500

Now it reboots after setting SSID, great.

Really appreciate your work, will try to combine it now with plant watering system ;)

Thx for porting the webserver, hope you will continue this project. I think it's one of the most useful ideas for this little inexpensive device.... have a nice weekend. 
marc

**Comment by dherrendoerfer** [comment]
Good luck with your project ! Please keep reporting issues.
